### PR TITLE
setSelection

### PR DESCRIPTION
**Pull request by imhoffd**
Added jQuery function setSelection for setting the selected text in a textfield or textarea. Updated test.html, but left readme and version numbers alone.

Tested in IE7, IE9, Opera, Firefox

### CODE REVIEW

**Comment by tdm00** [comment]
@dwieeb why did you close this PR, was there a problem with your code or it was just never accepted?  Your setSelection function seems to work for me whereas the replaceSelection function doesn't.  Just want to know if there are any known issues if I use your code.  Thanks.

**Comment by imhoffd** [comment]
I closed it because the repository owner never acknowledged it. So, I wrote my own [jQuery plugin](https://github.com/dwieeb/jquery-textrange) which is actively maintained by me and whomever wishes to fork it. It has all the functionality you would expect with all major browser support, even back to IE6.

**Comment by tdm00** [comment]
Excellent job Daniel, I'll use your plugin, thanks for your work!

On Wed, Aug 28, 2013 at 5:04 PM, Daniel Imhoff notifications@github.comwrote:

> I closed it because the repository owner never acknowledged it. So, I
> wrote my own jQuery plugin https://github.com/dwieeb/jquery-textrangewhich is actively maintained by me and whomever wishes to fork it. It has
> all the functionality you would expect with all major browser support, even
> back to IE6.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/localhost/jquery-fieldselection/pull/3#issuecomment-23447485
> .

## 

_Troy Murray_

**Comment by localhost** [comment]
Sorry, I'm not doing much webdev these days. Daniel, I'll link to your new plugin if you don't mind. :)

**Comment by imhoffd** [comment]
@tdm00 You're welcome!
@localhost Sure, absolutely! And no problem.

**Comment by tdm00** [comment]
Do either of you know of a good site, if one even exists, that has jQuery
plugins listed with additional meta information about each, much like
RubyToolbox?

On Wed, Aug 28, 2013 at 5:06 PM, Daniel Imhoff notifications@github.comwrote:

> @tdm00 https://github.com/tdm00 You're welcome!
> @localhost https://github.com/localhost Sure, absolutely! And no
> problem.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/localhost/jquery-fieldselection/pull/3#issuecomment-23447665
> .

## 

_Troy Murray_

**Comment by imhoffd** [comment]
Well, there is [unheap.com](http://www.unheap.com), which at least categorizes jQuery plugins.

**Comment by localhost** [comment]
Also there's the official one, but I guess you already know that:
http://plugins.jquery.com/

**Pull request closed without merging**
